<?php
namespace App\Services;
use App\Contracts\DomainInspectorInterface;use DateTimeImmutable;use DateTimeZone;use Illuminate\Support\Facades\Cache;use Iodev\Whois\Factory;use Pdp\Rules;
final class DomainInspector implements DomainInspectorInterface {
 private const PROVIDERS=['Google Workspace'=>['google.com','googlemail.com','aspmx.l.google.com','alt1.aspmx.l.google.com','alt2.aspmx.l.google.com','aspmx2.googlemail.com','aspmx3.googlemail.com'],'Microsoft 365'=>['mail.protection.outlook.com','outlook.com','hotmail.com','microsoft.com'],'Proofpoint'=>['pphosted.com','proofpoint.com'],'Mimecast'=>['mimecast.com'],'Barracuda'=>['barracudanetworks.com','ess.barracuda.com','cudamail.com']];
 public function registrableDomain(string $value): ?string { $host=strtolower(trim(str_contains($value,'@')?explode('@',$value,2)[1]:$value,'. ')); if($host===''||!filter_var($host,FILTER_VALIDATE_DOMAIN,FILTER_FLAG_HOSTNAME))return null; try{return Rules::fromPath(base_path('resources/public_suffix_list.dat'))->resolve($host)->registrableDomain()->toString() ?: $host;}catch(\Throwable){$parts=explode('.',$host);return count($parts)>=2?implode('.',array_slice($parts,-2)):$host;} }
 public function hasMx(string $domain): bool { return Cache::remember("v2:mx:$domain",3600,fn():bool=>checkdnsrr($domain,'MX')); }
 public function mxProvider(string $domain): string { return Cache::remember("v2:provider:$domain",3600,function()use($domain):string{$hosts=[];if(!getmxrr($domain,$hosts))return 'DNS Error';foreach(self::PROVIDERS as $provider=>$patterns)foreach($hosts as $host)foreach($patterns as $pattern)if(str_contains(strtolower($host),$pattern))return $provider;return 'Unknown / Self-hosted';}); }
 public function age(string $domain): array { return Cache::remember("v2:age:$domain",86400,function()use($domain):array{$out=['creation_date'=>'N/A','age_days'=>-1,'age_label'=>'Unknown'];try{$info=Factory::get()->createWhois()->loadDomainInfo($domain);$ts=$info?->creationDate;if(!$ts)return $out;$created=(new DateTimeImmutable('@'.$ts))->setTimezone(new DateTimeZone('UTC'));$days=(int)$created->diff(new DateTimeImmutable('now',new DateTimeZone('UTC')))->format('%a');return ['creation_date'=>$created->format('Y-m-d'),'age_days'=>$days,'age_label'=>$days>=365?intdiv($days,365).'y '.($days%365).'d':$days.'d'];}catch(\Throwable){return $out;}}); }
 public function organisation(string $domain): string { return Cache::remember("v2:org:$domain",86400,function()use($domain):string{try{$info=Factory::get()->createWhois()->loadDomainInfo($domain);$owner=trim((string)($info?->owner??''));return $owner!==''?$owner:'Private/No Org Info';}catch(\Throwable){return 'Lookup Failed';}}); }
}
