<?php
namespace App\Services;
use App\Contracts\DomainInspectorInterface;use App\Contracts\EmailValidatorInterface;use App\Contracts\SmtpProbeInterface;
final readonly class EmailValidationService implements EmailValidatorInterface {
 public function __construct(private DomainInspectorInterface $domains,private SmtpProbeInterface $smtp){}
 public function validate(string $email,array $disposableDomains,array $rolePrefixes,bool $companyLookup):array{$email=trim($email);$r=['Email'=>$email,'Domain'=>'N/A','Company/Org'=>'N/A (Pending)','Syntax Valid'=>false,'MX Record'=>false,'MX Provider'=>'N/A','Disposable'=>false,'Role-based'=>false,'SMTP Valid'=>false,'SMTP Code'=>null,'Catch-All'=>'N/A','Domain Created'=>'N/A','Domain Age'=>'Unknown','Domain Age (days)'=>-1,'Verdict'=>'❌ Invalid','Score'=>0];if(!filter_var($email,FILTER_VALIDATE_EMAIL)){return $this->finish($r,'❌ Invalid Syntax','N/A (Invalid Syntax)');}$r['Syntax Valid']=true;[$local,$host]=explode('@',$email,2);$domain=$this->domains->registrableDomain($host);$r['Domain']=$domain?:$host;if(!$domain)return $this->finish($r,'❌ Invalid Domain Format','N/A (Invalid Domain)');$r['Company/Org']=$companyLookup?$this->domains->organisation($domain):'Lookup Disabled';$r['Disposable']=in_array($domain,$disposableDomains,true);$r['Role-based']=in_array(strtolower($local),$rolePrefixes,true);$r['MX Record']=$this->domains->hasMx($domain);$r['MX Provider']=$this->domains->mxProvider($domain);$age=$this->domains->age($domain);$r['Domain Created']=$age['creation_date'];$r['Domain Age']=$age['age_label'];$r['Domain Age (days)']=$age['age_days'];if($r['MX Record']&&!$r['Disposable']){$probe=$this->smtp->verify($email,$domain);$r['SMTP Valid']=$probe['valid'];$r['SMTP Code']=$probe['code'];$catch=$this->smtp->catchAll($domain);$r['Catch-All']=$catch===true?'✅ Yes':($catch===false?'❌ No':'❓ Unknown');}$r['Verdict']=$r['Disposable']?'⚠️ Disposable':($r['Role-based']?'ℹ️ Role-based':($r['Syntax Valid']&&$r['MX Record']&&$r['SMTP Valid']?($r['Catch-All']==='✅ Yes'?'⚠️ Valid (Catch-All)':'✅ Valid'):'❌ Invalid'));$r['Score']=$this->score($r);return $r;}
 private function finish(array $r,string $verdict,string $org):array{$r['Verdict']=$verdict;$r['Company/Org']=$org;$r['Score']=$this->score($r);return $r;}
 private function score(array $r):int{$s=100;if(!$r['Syntax Valid'])$s-=100;elseif($r['Verdict']==='❌ Invalid Domain Format')$s-=95;elseif($r['Disposable'])$s-=90;elseif($r['Role-based'])$s-=30;else{if(!$r['MX Record'])$s-=70;if(!$r['SMTP Valid'])$s-=50;if(($r['Catch-All']??null)==='✅ Yes')$s-=20;}return max(0,$s);}
}
